name: ToriReid
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2142857
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#414042'
    - '#DECFC7'
    - '#888888'
    - '#5253AC'
    - '#CE5D70'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 1
purpose: []
